# Defining a list of nouns from the spacy document

nouns = [ token.text for token in doc if token.is_stop != True and token.is_punct !=True and token.pos_ == 'NOUN']

# Counting the frequency of each noun and selecting the top 10 most common ones

word_freq = Counter(nouns)
common_nouns = word_freq.most_common(10)
print(common_nouns)

# Defining a list of verbs from the spacy document

verbs = [ token.text for token in doc if token.is_punct !=True and token.pos_ == 'VERB']

# Counting the frequency of each verb and selecting the top 10 most common ones

print(Counter(verbs).most_common(10))


# Defining a function to sanitize names from a given text by replacing them with "[REDACTED]"

def sanitize_names(text):
    doc = nlp(text)
    redacted_sentences = []
    
    # Merging named entities to treat them as a single token
    
    for ent in doc.ents:
        ent.merge()
    
    # Checking each token and replacing the named entities tagged as PERSON with "[REDACTED]"
    
    for token in doc:
        if token.ent_type_ == 'PERSON':
            redacted_sentences.append("[REDACTED]")
        else:
            redacted_sentences.append(token.string)
    return "".join(redacted_sentences)
  

# Defining a function to sanitize locations from a given text by replacing them with "[REDACTED]"

def sanitize_locations(text):
    doc = nlp(text)
    redacted_sentences = []
    
    # Merging named entities to treat them as a single token
    
    for ent in doc.ents:
        ent.merge()
        
    # Checking each token and replacing the named entities tagged as GPE with "[REDACTED]"
    
    for token in doc:
        if token.ent_type_ == 'GPE':
            redacted_sentences.append("[REDACTED]")
        else:
            redacted_sentences.append(token.string)
    return "".join(redacted_sentences)
  
  
# Defining a function to tokenize a sentence using spacy

def spacy_tokenizer(sentence):
    mytokens = parser(sentence)
    
    # Lemmatizing each word, removing stopwords and punctuation
    
    mytokens = [ word.lemma_.lower().strip() if word.lemma_ != "-PRON-" else word.lower_ for word in mytokens ]
    mytokens = [ word for word in mytokens if word not in stopwords and word not in punctuations ]
    mytokens = " ".join([i for i in mytokens])
    return mytokens


# Defining a function to display the top n topics generated by a given LDA model and vectorizer

def selected_topics(model, vectorizer, top_n=10):
    for idx, topic in enumerate(model.components_):
        print("Topic %d:" % (idx))
        print([(vectorizer.get_feature_names()[i], topic[i])
                        for i in topic.argsort()[:-top_n - 1:-1]]) 


# Extracting named entities from each document in a pandas dataframe and storing them in a list

entities = []
for text in nlp.pipe(iter(bestdf['Description']), batch_size = 1000, n_threads=-1):  
  entities.append([(X.text, X.label_) for X in text.ents])
  print([(X.text, X.label_) for X in text.ents])

# Creating a new dataframe to store each named entity type for each document

index=range(0,13911)
full_df = pd.DataFrame(index = index, columns=['DOC NR','CARDINAL', 'ORDINAL', 'QUANTITY', 'MONEY', 'PERCENT', 'TIME', 'DATE', 'LANGUAGE', 'LAW', 'WORK_OF_ART', 'EVENT', 'PRODUCT', 'LOC', 'GPE', 'ORG', 'FAC', 'NORP', 'PERSON'])

# Storing each named entity in the appropriate column for the corresponding document

for index, doc in enumerate(entities):
    for entity, entity_type in doc:
        if pd.isna(full_df.at[index, entity_type]):
            full_df.at[index, entity_type] = entity
        else:
            full_df.at[index, entity_type] = full_df.at[index, entity_type] + ", {}".format(entity)